/* ------ ko'p ishlatiladigan string metodlari ---*/

let email = ' akhrorweb@gmail.com '

/*// lastIndeOf() <vazifasi oxirdagini aniqlayshni bacharadi
let reult = email.lastIndexOf('a')
console.log(reult)
//indexOf vasifasi birinchi turgan xaraktikani aniqlaydi
let reult = email.indexOf('a')
console.log(reult)*/

/*// slice() kesib beradi
let reult = email.slice(1,6)
console.log(reult)*/

/*// substr() qaysi sozlar kerah bolsa shuni oladi
let reult = email.substr(1, 3)
console.log(reult)*/

/*// repLace() < almashtirish >
let reult = email.replace('a', 'd')
console.log(reult)*/

/*// charAt() < -birinchi harakterni olib beradi >
let reult = email.charAt(1)
console.log(reult)*/

/* // toUpperCase() - toLowerCase() kata va kichkina qiladi
let reult = email.toLowerCase()
console.log(reult)*/

/* // trim()
let reult = email.trim()
console.log(reult.length, email.length)*/

// split()
let reult = email.split('')
console.log(reult)